using Kpi.Application.Common;
using Kpi.Domain.Auditing;
using Kpi.Domain.Periods;
using Kpi.Domain.Kpis;

namespace Kpi.Application;

/// <summary>Governed Period planning and revision operations.</summary>
public sealed class PeriodOperations(InMemoryKpiStore store, IClock clock)
{
    public ApplicationResult<KpiPeriod> Create(ActorContext actor, string code, DateTimeOffset starts, DateTimeOffset ends)
    {
        if (!actor.Can(KpiCapability.PlanPeriod)) return ApplicationResult<KpiPeriod>.Failure("AUTHORIZATION_DENIED", "Actor cannot plan a Period.", 403);
        try { var period = KpiPeriod.Create(actor.OrganizationId, code, starts, ends, actor.ActorId); return ApplicationResult<KpiPeriod>.Success(store.AddPeriod(period, AuditRecord.Create(actor.OrganizationId, actor.ActorId, "KPI_PERIOD", period.Id, AuditEventType.PeriodChanged, clock.UtcNow, actor.CorrelationId, summary: "Created"))); }
        catch (Exception ex) when (ex is ArgumentException or KpiDomainException) { return ApplicationResult<KpiPeriod>.Failure("VALIDATION", ex.Message); }
    }
    public ApplicationResult<KpiPeriod> Select(ActorContext actor, Guid periodId, Guid definitionId, Guid versionId)
    { var period = store.FindPeriod(periodId); if (period is null) return ApplicationResult<KpiPeriod>.Failure("RESOURCE_NOT_FOUND", "Period was not found.", 404); if (!actor.Can(KpiCapability.PlanPeriod) || period.PlannerId != actor.ActorId) return ApplicationResult<KpiPeriod>.Failure("AUTHORIZATION_DENIED", "Only the Planner can edit this Period.", 403); try { period.Select(definitionId, versionId); return ApplicationResult<KpiPeriod>.Success(period); } catch (KpiDomainException ex) { return ApplicationResult<KpiPeriod>.Failure("LIFECYCLE_CONFLICT", ex.Message, 409); } }
    public ApplicationResult<KpiPeriod> Submit(ActorContext actor, Guid periodId)
    { var period = store.FindPeriod(periodId); if (period is null) return ApplicationResult<KpiPeriod>.Failure("RESOURCE_NOT_FOUND", "Period was not found.", 404); if (period.PlannerId != actor.ActorId) return ApplicationResult<KpiPeriod>.Failure("AUTHORIZATION_DENIED", "Only the Planner can submit this Period.", 403); try { period.Submit(); store.AddAudit(AuditRecord.Create(actor.OrganizationId, actor.ActorId, "KPI_PERIOD", period.Id, AuditEventType.Submitted, clock.UtcNow, actor.CorrelationId)); return ApplicationResult<KpiPeriod>.Success(period); } catch (KpiDomainException ex) { return ApplicationResult<KpiPeriod>.Failure("LIFECYCLE_CONFLICT", ex.Message, 409); } }
    public ApplicationResult<KpiPeriod> Approve(ActorContext actor, Guid periodId)
    { var period = store.FindPeriod(periodId); if (period is null) return ApplicationResult<KpiPeriod>.Failure("RESOURCE_NOT_FOUND", "Period was not found.", 404); if (!actor.Can(KpiCapability.ApprovePeriod)) return ApplicationResult<KpiPeriod>.Failure("AUTHORIZATION_DENIED", "Actor cannot approve a Period.", 403); try { period.Approve(actor.ActorId); store.AddAudit(AuditRecord.Create(actor.OrganizationId, actor.ActorId, "KPI_PERIOD", period.Id, AuditEventType.Approved, clock.UtcNow, actor.CorrelationId)); return ApplicationResult<KpiPeriod>.Success(period); } catch (KpiDomainException ex) { return ApplicationResult<KpiPeriod>.Failure("LIFECYCLE_CONFLICT", ex.Message, 409); } }
    public IReadOnlyList<KpiPeriod> List() => store.Periods;
    public ApplicationResult<KpiPeriod> Reject(ActorContext actor, Guid periodId, string comment)
    { var period = store.FindPeriod(periodId); if (period is null) return ApplicationResult<KpiPeriod>.Failure("RESOURCE_NOT_FOUND", "Period was not found.", 404); if (!actor.Can(KpiCapability.ApprovePeriod)) return ApplicationResult<KpiPeriod>.Failure("AUTHORIZATION_DENIED", "Actor cannot reject a Period.", 403); try { period.Reject(comment); store.AddAudit(AuditRecord.Create(actor.OrganizationId, actor.ActorId, "KPI_PERIOD", period.Id, AuditEventType.Rejected, clock.UtcNow, actor.CorrelationId, reason: comment)); return ApplicationResult<KpiPeriod>.Success(period); } catch (KpiDomainException ex) { return ApplicationResult<KpiPeriod>.Failure("LIFECYCLE_CONFLICT", ex.Message, 409); } }
    public ApplicationResult<KpiPeriod> ReturnToDraft(ActorContext actor, Guid periodId)
    { var period = store.FindPeriod(periodId); if (period is null) return ApplicationResult<KpiPeriod>.Failure("RESOURCE_NOT_FOUND", "Period was not found.", 404); if (!actor.Can(KpiCapability.PlanPeriod)) return ApplicationResult<KpiPeriod>.Failure("AUTHORIZATION_DENIED", "Actor cannot edit a Period.", 403); try { period.ReturnToDraft(actor.ActorId); store.AddAudit(AuditRecord.Create(actor.OrganizationId, actor.ActorId, "KPI_PERIOD", period.Id, AuditEventType.PeriodChanged, clock.UtcNow, actor.CorrelationId, summary: "Rejected to Draft")); return ApplicationResult<KpiPeriod>.Success(period); } catch (KpiDomainException ex) { return ApplicationResult<KpiPeriod>.Failure("LIFECYCLE_CONFLICT", ex.Message, 409); } }
    public ApplicationResult<KpiPeriod> Amend(ActorContext actor, Guid periodId, Guid approverId, IReadOnlyDictionary<Guid, Guid> selections, string reason)
    { var period = store.FindPeriod(periodId); if (period is null) return ApplicationResult<KpiPeriod>.Failure("RESOURCE_NOT_FOUND", "Period was not found.", 404); if (!actor.Can(KpiCapability.PlanPeriod)) return ApplicationResult<KpiPeriod>.Failure("AUTHORIZATION_DENIED", "Actor cannot amend a Period.", 403); try { period.Amend(actor.ActorId, approverId, selections, reason); store.AddAudit(AuditRecord.Create(actor.OrganizationId, actor.ActorId, "KPI_PERIOD", period.Id, AuditEventType.PeriodChanged, clock.UtcNow, actor.CorrelationId, reason: reason)); return ApplicationResult<KpiPeriod>.Success(period); } catch (KpiDomainException ex) { return ApplicationResult<KpiPeriod>.Failure("LIFECYCLE_CONFLICT", ex.Message, 409); } }
    public ApplicationResult<KpiPeriod> Activate(ActorContext actor, Guid periodId)
    { var period = store.FindPeriod(periodId); if (period is null) return ApplicationResult<KpiPeriod>.Failure("RESOURCE_NOT_FOUND", "Period was not found.", 404); try { period.Activate(clock.UtcNow); store.AddAudit(AuditRecord.Create(actor.OrganizationId, actor.ActorId, "KPI_PERIOD", period.Id, AuditEventType.PeriodChanged, clock.UtcNow, actor.CorrelationId, summary: "Activated")); return ApplicationResult<KpiPeriod>.Success(period); } catch (KpiDomainException ex) { return ApplicationResult<KpiPeriod>.Failure("LIFECYCLE_CONFLICT", ex.Message, 409); } }
    public ApplicationResult<KpiPeriod> Close(ActorContext actor, Guid periodId)
    { var period = store.FindPeriod(periodId); if (period is null) return ApplicationResult<KpiPeriod>.Failure("RESOURCE_NOT_FOUND", "Period was not found.", 404); try { period.Close(clock.UtcNow); store.AddAudit(AuditRecord.Create(actor.OrganizationId, actor.ActorId, "KPI_PERIOD", period.Id, AuditEventType.PeriodChanged, clock.UtcNow, actor.CorrelationId, summary: "Closed")); return ApplicationResult<KpiPeriod>.Success(period); } catch (KpiDomainException ex) { return ApplicationResult<KpiPeriod>.Failure("LIFECYCLE_CONFLICT", ex.Message, 409); } }
}
